### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dmontagu** [vinissimus/async-asgi-testclient#12]
Any chance this could be released with a different, more permissive license?

Both of the frameworks you suggest for use with this library (Starlette and Quart) make use of more permissive open source licenses (BSD for Starlette; MIT for Quart).

Given how much activity there is in the ASGI ecosystem right now (and also the extent to which other projects all have permissive licenses), I would be hesitant to start building around a less established dependency with a non-permissive license -- my fear would be that a different project with a more compatible license would end up with more wide-spread adoption in the long term.

(I would totally understand if you prefer to keep the code GPL licensed, just figured it was worth asking.)

**Comment by masipcat** [comment]
I don't see any problem to change the license to MIT/BSD/Apache. What do you think @jordic  @dmanchon?

**Comment by jordic** [comment]
Sounds good!
