### ISSUE TITLE
Bug: websocket scope error

### ISSUE THREAD

**Issue by yanyongyu** [vinissimus/async-asgi-testclient#43]
According to asgi document, the websocket connection scheme should be `ws` or `wss`, but get `http`

This cause test failure for quart `0.15+`/`0.16+` (Error `BadRequest`)

https://github.com/vinissimus/async-asgi-testclient/blob/a86e5774af88a4918ef7b0e4874307e8e308d7e7/async_asgi_testclient/websocket.py#L115-L123

Reference: https://asgi.readthedocs.io/en/latest/specs/www.html#websocket-connection-scope

**Comment by masipcat** [comment]
Fix released in v1.4.9
